/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/city-map-framed-wall-art-print-amsterdam-0605a5f3e2784a5aad2127170d63e237
Title: City Map Framed Wall Art Print, Amsterdam
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.48, 0]}>
          <mesh geometry={nodes.City_Map_Amsterdam_50x50_PRINT_0.geometry} material={materials.PRINT} />
          <mesh geometry={nodes.City_Map_Amsterdam_50x50_FRAME_0.geometry} material={materials.FRAME} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
